---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/parts/{part_id}/children":
    parameters:
    - name: part_id
      in: path
      description: part_id
      required: true
      schema:
        type: integer
    get:
      summary: children part
      responses:
        '200':
          description: successful
    put:
      summary: children_add part
      responses:
        '200':
          description: successful
    delete:
      summary: children_delete part
      responses:
        '200':
          description: successful
  "/api/v1/parts/{part_id}/parents":
    parameters:
    - name: part_id
      in: path
      description: part_id
      required: true
      schema:
        type: string
    get:
      summary: parents part
      responses:
        '200':
          description: successful
    put:
      summary: parents_add part
      responses:
        '200':
          description: successful
    delete:
      summary: parents_delete part
      responses:
        '200':
          description: successful
  "/api/v1/parts":
    get:
      summary: list parts
      responses:
        '200':
          description: successful
    post:
      summary: create part
      responses:
        '200':
          description: successful
  "/api/v1/parts/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show part
      responses:
        '200':
          description: successful
    patch:
      summary: update part
      responses:
        '200':
          description: successful
    put:
      summary: update part
      responses:
        '200':
          description: successful
    delete:
      summary: delete part
      responses:
        '200':
          description: successful
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
